### ISSUE TITLE
Add to SugarSS docs

### ISSUE THREAD

**Issue by ai** [idleberg/atom-build-sugarss#1]
Feel free to send PR to `postcss/sugarss` README with your link

**Comment by idleberg** [comment]
Done, thanks for the suggestion!

By the way… I'm rather new to PostCSS, do you think it makes more sense to name the build provider `build-postcss-sugarss`? So far I followed the policy to name the provider after the binary building/compiling. The `build` package doesn't set any standards, but I thought it makes sense (and I remember SublimeLinter does it that way)

**Comment by ai** [comment]
@idleberg we have name policy only for PostCSS plugin. You have Build plugin, so use Build name policy :D
